##
## Deployment of PlantUML Service
##

apiVersion: v1
kind: Namespace
metadata:
  name: plantuml

---
apiVersion: v1
kind: Service
metadata:
  name: plantuml
  namespace: plantuml
  labels:
    app: plantuml
spec:
  selector:
    app: plantuml
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml
  namespace: plantuml
  labels:
    app: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
      - name: plantuml
        image: plantuml/plantuml-server:jetty
        ports:
        - containerPort: 8080
---
