apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: plantuml
  namespace: plantuml
spec:
  virtualhost:
    fqdn: plantuml.example.com
  routes:
    - conditions:
        - prefix: /
      services:
        - name: plantuml
          port: 80